import type { Metadata } from "next";
import CookieBanner from "@/components/CookieBanner/CookieBanner";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de" className="h-full antialiased">
      <body className=" min-h-full">
        {children}
        <CookieBanner />
      </body>
    </html>
  );
}
